### ISSUE TITLE
Install Error - eirannejad/pyRevit

### ISSUE THREAD

**Issue by FelipeBreia** [eirannejad/pyRevit#966]
#677  #257 
**Hey!**

I am not sure how to use the site. I'm sorry if I'm wrong.

I installed the latest version of pyrevit and when opening the program this error appeared. What do I need to do?

![image](https://user-images.githubusercontent.com/69577812/89996533-4b362700-dc61-11ea-98de-406c9679b746.png)

Thank you!

**Desktop:**
 - OS: Win 10 64x
 - pyRevit Version 4.8.0

**Comment by djdarkstream** [comment]
I have the same error after updating to 4.8.0, I then remov ed PyRevit entirely and reinstalled, error remains. After reinstalling the first boot gave the same error again and the second boot the error changes a bit see screenshot:
![error after 2nd boot](https://user-images.githubusercontent.com/5404802/90003472-6bcba480-dc94-11ea-9ded-ea51ae596059.png)

**Comment by eirannejad** [comment]
Go under `%APPDATA%/pyRevit/2021` and upload the `.log` file for the runtime please. This will let me see why the runtime compilation failed

**Comment by djdarkstream** [comment]
I'll remove the old version, move old logs, install new version and upload
the new logs, maybe today, probably tomorrow.

- Dark

**Comment by eirannejad** [comment]
Okay I think I've found the issue. There has been an API change in Revit 2021.1 that I have adopted but it broke 2021.0
I'll publish the new installer by Monday
