### ISSUE TITLE
How to make pyrevit work with CPython 3.8.5 ?

### ISSUE THREAD

**Issue by MohamedAliRashad** [eirannejad/pyRevit#1288]
**Describe the bug**
I can't import `script` from `pyrevit`, it gives me a `clr` error message

**To Reproduce**
1. Use Python3 with `#! python3` in the top of your script
2. Add this line in the imports section `from pyrevit import script`
3. Run the script

**Expected behavior**
No … error

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]

![Screenshot from 2021-06-25 16-34-50](https://user-images.githubusercontent.com/26205298/123440667-5244fa00-d5d3-11eb-9570-d53f1ef784e8.png)

**Comment by CyrilWaechter** [comment]
Currently I just do not use `pyrevit` module. I had to recreate any feature I wanted to use in cpython.

**Comment by alexdaversa** [comment]
It's specifically getting hung up here for me:

```
CPython Traceback:
AttributeError : module 'clr' has no attribute 'AddReferenceToFileAndPath'
 File "C:\Users\adaversa\Documents\Git\pyKSS-local\pyKSS.extension\hooks\doc-opened.py", line 14, in <module>
from pyrevit import EXEC_PARAMS
 File "C:\Users\adaversa\AppData\Roaming\pyRevit-Master\pyrevitlib\pyrevit\__init__.py", line 85, in <module>
 from pyrevit.framework import Process
 File "C:\Users\adaversa\AppData\Roaming\pyRevit-Master\pyrevitlib\pyrevit\framework.py", line 89, in <module>
 clr.AddReferenceToFileAndPath(ipy_dllpath)

pyRevitLabs.PythonNet
at Python.Runtime.Runtime.CheckExceptionOccurred()
 at Python.Runtime.PyScope.Exec(String code, IntPtr _globals, IntPtr _locals)
 at PyRevitLabs.PyRevit.Runtime.CPythonEngine.Execute(ScriptRuntime& runtime)
```

Which seems like the cpython clr can't AddReferenceToFileAndPath

**Comment by tillbaum** [comment]
pythonnet only has clr.AddReference() not AddReferenceToFileAndPath from what I know.
So you would have to do this instead: https://stackoverflow.com/questions/49998309/import-of-dll-with-pythonnet
