### ISSUE TITLE
Keynote Manager stopped working with Revit 22.1.1.516 Update

### ISSUE THREAD

**Issue by scottofazphx** [eirannejad/pyRevit#1371]
Our Keynote file is hosted on autodesk docs and has been working perfect up until this last revit update now when we try to open it we get a "NoneType" object has no attribute value error
![Screenshot 2021-11-02 145335](https://user-images.githubusercontent.com/36394998/139957049-465240d7-b1ff-4600-b0b9-f9e4fc561980.png)
.

**Comment by cloghmani3182** [comment]
We are receiving the same exact error message for Manage Keynotes on one of my office's project files.  Can we please find a fix for this error message?  Also, does anyone know of a temporary workaround while this is being resolved with regard to keynoting?

**Comment by nterranova-fsb** [comment]
We are seeing this error as well. We are in a Revit 2020 (20.2.40.65) project, but noticed this error popped up when we upgrade the Desktop Connector from 14.3 to 15.1. I will update once I downgrade to verify that solves the issue.

**Comment by ckuhnMPLS** [comment]
Same issue and just posted as well.

**Comment by aconchado** [comment]
We're getting the same error with Revit 2021.1.4 and Desktop Connector 15.0.0.1540.

**Comment by olalancette** [comment]
Here is the error if we remove the try/except:

`Traceback (most recent call last):
 File "C:\pyRevit\main\extensions\pyRevitTools.extension\pyRevit.tab\Drawing Set.panel\Keynotes.pushbutton\script.py", line 1376, in <module>
 File "C:\pyRevit\main\extensions\pyRevitTools.extension\pyRevit.tab\Drawing Set.panel\Keynotes.pushbutton\script.py", line 337, in __init__
 File "C:\pyRevit\main\extensions\pyRevitTools.extension\pyRevit.tab\Drawing Set.panel\Keynotes.pushbutton\script.py", line 585, in _determine_kfile
 File "C:\pyRevit\main\pyrevitlib\pyrevit\interop\adc.py", line 187, in sync_file
 File "C:\pyRevit\main\pyrevitlib\pyrevit\interop\adc.py", line 182, in is_synced
AttributeError: 'NoneType' object has no attribute 'Value'`

The error seems to be in the function  "adc._get_item_property_id_value", it is looking for prop_def = 'LocalState' but it seems that they changed the Id to "DesktopConnector.Core.LocalState"

If we change line 179 with : 
`prop_val = _get_item_property_id_value(adc, drive, item, 'DesktopConnector.Core.LocalState')
`
It will work, but I would suggest to add a version checker somewhere >15.

**Comment by cattaca248** [comment]
I have the same issue. I tried scouting for the lines of code referenced in the fix above and no luck. Really need the keynote manager working again!

**Comment by olalancette** [comment]
@cattaca248 see pull request : #1398 (in the "Files changed" tab)

**Comment by cattaca248** [comment]
@olalancette Thank you so much for the *nudge*. I found the location where the reference needed to be changed and got the updated code. All fixed!
