### PR TITLE
Implement configuration migration for admin installs and refactor config file handling

### LINKED ISSUE #3101: [Bug]: Admin Installer Fails to Register Clone and Attach
## Bug : Admin Installer Fails to Register Clone and Attach

The admin installer (pyRevit_6.0.0.26032_admin_signed.exe) completes without error and deploys files to `C:\Program Files\pyRevit-Master` correctly. However, it does not register the clone or create attachments to any installed Revit version. After install, `pyrevit env` shows empty Registered Clones and Attachments sections while Installed Revits are detected correctly. pyRevit tabs do not appear in any Revit version.

**Workaround:**

```
pyrevit clones add master "C:\Program Files\pyRevit-Master" --force
pyrevit attach master default --installed --allusers
```

This is independently confirmed by @alitehami in #3063.

### ⏲️ Expected behavior

Admin installer should register the clone and attach to all detected Revit versions automatically.

<details><summary>Details</summary>
<p>

### ✈ Pre-Flight checks

- [x] I **don't have SentinelOne** antivirus installed (see above for the solution)
- [x] I have **searched in the issues** (open and closed) but couldn't find a similar issue
- [x] I have **searched in the [pyRevit Forum](https://discourse.pyrevitlabs.io)** for similar issues
- [x] I already **followed the [installation troubleshooting guide](https://pyrevitlabs.notion.site/Installation-issues-f6495adb56254e9e8021f8a68e3b2ab7) thoroughly**
- [x] I am using the **latest pyRevit Version**

### 🐞 Describe the bug

Two issues found after clean install of v6.0.0.26032 using the admin installer (previous versions fully uninstalled, computer restarted).

### Bug 1: Admin Installer Fails to Register Clone and Attach

The admin installer (pyRevit_6.0.0.26032_admin_signed.exe) completes without error and deploys files to `C:\Program Files\pyRevit-Master` correctly. However, it does not register the clone or create attachments to any installed Revit version. After install, `pyrevit env` shows empty Registered Clones and Attachments sections while Installed Revits are detected correctly. pyRevit tabs do not appear in any Revit version.

**Workaround:**

```
pyrevit clones add master "C:\Program Files\pyRevit-Master" --force
pyrevit attach master default --installed --allusers
```

This is independently confirmed by @alitehami in #3063.

### Bug 2: pyrevit.forms WPF Crash (ResourceReferenceKeyNotFoundException)

Any extension tool that calls `pyrevit.forms` to display a WPF dialog (CommandSwitchWindow, SelectFromList, or any WPF-based prompt) crashes with:

```
User script calls pyrevit.forms dialog
  -> forms/__init__.py, line 720, in show()
  -> forms/__init__.py, line 677, in __init__()
  -> AttributeError: 'module' object has no attribute
     'ResourceReferenceKeyNotFoundException'

Script Executor Traceback:
System.MissingMemberException: 'module' object has no
  attribute 'ResourceReferenceKeyNotFoundException'
  at PyRevitLabs.PyRevit.Runtime.IronPythonEngine.Execute()
```

The crash is inside pyRevit's own forms library, not in custom extension code. The new C# Loader bootstrap sequence does not appear to load WPF assemblies in a way that makes `System.Windows.ResourceReferenceKeyNotFoundException` available to the IronPython runtime. Under 5.3.1, these assemblies resolved correctly.

This affects any custom extension using `pyrevit.forms` for UI dialogs. Tools that do not depend on `pyrevit.forms` appear unaffected. All affected tools work correctly on 5.3.1.25308.

### Bug 3: CLI Null Reference on Running Revit Instances

`pyrevit env` produces an error under the Running Revit Instances section:

```
Error: Object reference not set to an instance of an object.
```

Low severity, informational only.

### ⌨ Error/Debug Message

```shell
IronPython Traceback:
Traceback (most recent call last):
  File "...\script.py", in <module>
  File "...\script.py", in main
  File "...\script.py", in choose_mode
  File "C:\Program Files\pyRevit-Master\pyrevitlib\pyrevit\forms\__init__.py", line 720, in show
  File "C:\Program Files\pyRevit-Master\pyrevitlib\pyrevit\forms\__init__.py", line 677, in __init__
AttributeError: 'module' object has no attribute 'ResourceReferenceKeyNotFoundException'

Script Executor Traceback:
System.MissingMemberException: 'module' object has no attribute 'ResourceReferenceKeyNotFoundException'
  at Microsoft.Scripting.Runtime.LightExceptions.ThrowException(LightException lightEx)
  at Microsoft.Scripting.Runtime.LightExceptions.CheckAndThrow(Object value)
  at PyRevitLabs.PyRevit.Runtime.IronPythonEngine.Execute(ScriptRuntime& runtime)
```

### ♻️ To Reproduce

Uninstall all previous pyRevit versions. Restart computer.
Install pyRevit 6.0.0.26032 using the Admin/All Users EXE installer.
Open Revit. Observe pyRevit tabs do not appear.
Run pyrevit env in command prompt. Observe empty Registered Clones and Attachments sections.
Manually register and attach via CLI:

   pyrevit clones add master "C:\Program Files\pyRevit-Master" --force
   pyrevit attach master default --installed --allusers

Open Revit. pyRevit tabs now appear.
Run any extension tool that calls pyrevit.forms to display a WPF dialog.
Observe ResourceReferenceKeyNotFoundException crash.
Uninstall 6.0.0, reinstall 5.3.1.25308. All tools work correctly.

### ⏲️ Expected behavior

Admin installer should register the clone and attach to all detected Revit versions automatically.
pyrevit.forms WPF dialogs should function identically to 5.3.1.
pyrevit env should not throw null reference errors under Running Revit Instances.

### 🖥️ Hardware and Software Setup (please complete the following information)

```shell
C:\Users\jgriffith>pyrevit env
==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive/image)
master | Branch: "master" | Version: "6.0.0.26032+2145" | Path: "C:\Program Files\pyRevit-Master"
==> Attachments
master | Product: "2026 First Customer Ship" | Engine: DEFAULT | Path: "C:\Program Files\pyRevit-Master" | AllUsers
master | Product: "2025 First Customer Ship" | Engine: DEFAULT | Path: "C:\Program Files\pyRevit-Master" | AllUsers
master | Product: "2024.3.4" | Engine: DEFAULT | Path: "C:\Program Files\pyRevit-Master" | AllUsers
master | Product: "2023.1.8" | Engine: DEFAULT | Path: "C:\Program Files\pyRevit-Master" | AllUsers
master | Product: "2022.1.8" | Engine: DEFAULT | Path: "C:\Program Files\pyRevit-Master" | AllUsers
==> Installed Extensions
==> Default Extension Search Path
C:\Users\jgriffith\AppData\Roaming\pyRevit\Extensions
==> Extension Search Paths
==> Extension Sources - Default
https://github.com/pyrevitlabs/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
==> Installed Revits
2026 First Customer Ship | Version: 26.0.4.409 | Build: 20250227_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2026\"
2025 First Customer Ship | Version: 25.0.2.419 | Build: 20240307_1300(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2025\"
2024.3.4 | Version: 24.3.40.26 | Build: 20250918_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2024\"
2023.1.8 | Version: 23.1.80.30 | Build: 20250724_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2023\"
2022.1.8 | Version: 22.1.80.32 | Build: 20241107_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2022\"
==> Running Revit Instances
Error: Object reference not set to an instance of an object.
Run with "--debug" option to see debug messages
```

### Additional context

Related to #3063. The installer attachment failure and the pyrevit.forms WPF crash both appear to stem from the C# Loader rewrite (#2647). All issues are fully reproducible and all affected functionality works correctly on 5.3.1.25308.

</p>
</details>

### LINKED ISSUE #3441: [Bug]: Revit 2027 — pyRevit loads (PyRevitLoader, NoError) but no ribbon; IronPython engine never runs and no log is written
### ✈ Pre-Flight checks

- [x] I **don't have SentinelOne** antivirus installed (see above for the solution)
- [x] I have **searched in the issues** (open and closed) but couldn't find a similar issue
- [x] I have **searched in the [pyRevit Forum](https://discourse.pyrevitlabs.io)** for similar issues
- [x] I already **followed the [installation troubleshooting guide](https://pyrevitlabs.notion.site/Installation-issues-f6495adb56254e9e8021f8a68e3b2ab7) thoroughly**
- [x] I am using the **latest pyRevit Version**

### 🐞 Describe the bug

On Revit 2027, pyRevit 6.4.0.26100+0515 loads on the .NET side but no pyRevit ribbon/tab ever appears.

What was tried and confirmed:
- pyRevit was initially attached to 2027 as **AllUsers**, which Revit 2027 rejects for unsigned add-ins (per #3275). Re-attached as **CurrentUser** — Revit 2027 now loads the add-in cleanly.
- Revit journal shows PyRevitLoader loading with no error:
  `[Jrn.AddInManifest] ... AddInName: PyRevitLoader ... AddInVersion: 2.7.12.0 ... AddInCodeSigningStatus: Signed ... AddInLoadFailureMessage: NoError`
  `The add-in folder 'C:\Program Files\pyRevit-Master\bin\netcore\engines\IPY2712PR' was registered for the context 'DEFAULT'.`
- However there are **no pyRevit `Added pushbutton…` entries anywhere in the journal** (every other add-in logs theirs), and **no pyRevit log is written to %APPDATA%\pyRevit\ even with `filelogging enable` + `logging debug`**. So PyRevitLoader loads on the managed side, but the IronPython (IPY2712PR) startup never executes any Python and the ribbon is never built.
- `pyrevit caches clear --all` + restart Revit: no change.
- The engine folder is fully populated, including `pyRevitLabs.PyRevit.Runtime.2027.dll`, `pyRevitLoader.dll`, and the full IronPython set — so no missing/blocked binaries.
- Antivirus ruled out: machine runs Webroot (not SentinelOne); disabling Webroot real-time protection made no difference, and the engine DLLs are all present.

Net: the loader loads with NoError, but the managed startup silently aborts before any Python runs, so there is no tab and no log. Appears to be a 2027 / .NET 10 engine-startup gap rather than a local config issue. Happy to provide the full journal.

### ⌨ Error/Debug Message

```shell
No error is surfaced anywhere.
- Revit journal: AddInCodeSigningStatus: Signed, AddInLoadFailureMessage: NoError for pyRevit.addin.
- No pyRevit log file is created in %APPDATA%\pyRevit\ even after `pyrevit configs logging debug` + `pyrevit configs filelogging enable` and relaunching Revit 2027.

Can provide the full Revit journal and Windows Event Viewer entries on request.
```

### ♻️ To Reproduce

_No response_

### ⏲️ Expected behavior

_No response_

### 🖥️ Hardware and Software Setup (please complete the following information)

```shell
pyrevit env:

Registered Clones:
  master | Branch: "master" | Version: "6.4.0.26100+0515" | Path: "C:\Program Files\pyRevit-Master"
Attachments:
  master | Product: "2027" | Engine: DEFAULT (2712) | Path: "C:\Program Files\pyRevit-Master"  (CurrentUser)
Installed Revits:
  2027 | Version: 27.0.4.412  (running build 20260527_1515 (x64), 2027.1)
User Environment:
  Microsoft Windows 11 [Version 10.0.26200]
  Latest Installed .Net Framework: 10.0.9
  Active CPython Engine Version: 0
  pyRevit CLI v6.4.0.26100+0515

Antivirus: Webroot SecureAnywhere (real-time protection disabled during testing, no change).
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by jmcouffin**
Added methods to migrate admin config files to ProgramData and check for clones. Updated IsInstallAllUsers method to use PyRevitInstallScope. Adjusted paths for config file retrieval in PyRevitConfig and PyRevitConfig.csproj. Enhanced pyRevit installation script to create all-users marker and execute post-install commands.

### CODE REVIEW

**Comment by jmcouffin** [comment]
## TEST
admin silent install → pyrevit env → optional Revit 2027 ribbon check.
