### ISSUE TITLE
[Bug]: Admin Installer Fails to Register Clone and Attach

### ISSUE THREAD

**Issue by jergrif73** [eirannejad/pyRevit#3101]
## Bug : Admin Installer Fails to Register Clone and Attach

The admin installer (pyRevit_6.0.0.26032_admin_signed.exe) completes without error and deploys files to `C:\Program Files\pyRevit-Master` correctly. However, it does not register the clone or create attachments to any installed Revit version. After install, `pyrevit env` shows empty Registered Clones and Attachments sections while Installed Revits are detected correctly. pyRevit tabs do not appear in any Revit version.

**Workaround:**

```
pyrevit clones add master "C:\Program Files\pyRevit-Master" --force
pyrevit attach master default --installed --allusers
```

This is independently confirmed by @alitehami in #3063.

### ⏲️ Expected behavior

Admin installer should register the clone and attach to all detected Revit versions automatically.

<details><summary>Details</summary>
<p>

### ✈ Pre-Flight checks

- [x] I **don't have SentinelOne** antivirus installed (see above for the solution)
- [x] I have **searched in the issues** (open and closed) but couldn't find a similar issue
- [x] I have **searched in the [pyRevit Forum](https://discourse.pyrevitlabs.io)** for similar issues
- [x] I already **followed the [installation troubleshooting guide](https://pyrevitlabs.notion.site/Installation-issues-f6495adb56254e9e8021f8a68e3b2ab7) thoroughly**
- [x] I am using the **latest pyRevit Version**

### 🐞 Describe the bug

Two issues found after clean install of v6.0.0.26032 using the admin installer (previous versions fully uninstalled, computer restarted).

### Bug 1: Admin Installer Fails to Register Clone and Attach

The admin installer (pyRevit_6.0.0.26032_admin_signed.exe) completes without error and deploys files to `C:\Program Files\pyRevit-Master` correctly. However, it does not register the clone or create attachments to any installed Revit version. After install, `pyrevit env` shows empty Registered Clones and Attachments sections while Installed Revits are detected correctly. pyRevit tabs do not appear in any Revit version.

**Workaround:**

```
pyrevit clones add master "C:\Program Files\pyRevit-Master" --force
pyrevit attach master default --installed --allusers
```

This is independently confirmed by @alitehami in #3063.

### Bug 2: pyrevit.forms WPF Crash (ResourceReferenceKeyNotFoundException)

Any extension tool that calls `pyrevit.forms` to display a WPF dialog (CommandSwitchWindow, SelectFromList, or any WPF-based prompt) crashes with:

```
User script calls pyrevit.forms dialog
  -> forms/__init__.py, line 720, in show()
  -> forms/__init__.py, line 677, in __init__()
  -> AttributeError: 'module' object has no attribute
     'ResourceReferenceKeyNotFoundException'

Script Executor Traceback:
System.MissingMemberException: 'module' object has no
  attribute 'ResourceReferenceKeyNotFoundException'
  at PyRevitLabs.PyRevit.Runtime.IronPythonEngine.Execute()
```

The crash is inside pyRevit's own forms library, not in custom extension code. The new C# Loader bootstrap sequence does not appear to load WPF assemblies in a way that makes `System.Windows.ResourceReferenceKeyNotFoundException` available to the IronPython runtime. Under 5.3.1, these assemblies resolved correctly.

This affects any custom extension using `pyrevit.forms` for UI dialogs. Tools that do not depend on `pyrevit.forms` appear unaffected. All affected tools work correctly on 5.3.1.25308.

### Bug 3: CLI Null Reference on Running Revit Instances

`pyrevit env` produces an error under the Running Revit Instances section:

```
Error: Object reference not set to an instance of an object.
```

Low severity, informational only.

### ⌨ Error/Debug Message

```shell
IronPython Traceback:
Traceback (most recent call last):
  File "...\script.py", in <module>
  File "...\script.py", in main
  File "...\script.py", in choose_mode
  File "C:\Program Files\pyRevit-Master\pyrevitlib\pyrevit\forms\__init__.py", line 720, in show
  File "C:\Program Files\pyRevit-Master\pyrevitlib\pyrevit\forms\__init__.py", line 677, in __init__
AttributeError: 'module' object has no attribute 'ResourceReferenceKeyNotFoundException'

Script Executor Traceback:
System.MissingMemberException: 'module' object has no attribute 'ResourceReferenceKeyNotFoundException'
  at Microsoft.Scripting.Runtime.LightExceptions.ThrowException(LightException lightEx)
  at Microsoft.Scripting.Runtime.LightExceptions.CheckAndThrow(Object value)
  at PyRevitLabs.PyRevit.Runtime.IronPythonEngine.Execute(ScriptRuntime& runtime)
```

### ♻️ To Reproduce

Uninstall all previous pyRevit versions. Restart computer.
Install pyRevit 6.0.0.26032 using the Admin/All Users EXE installer.
Open Revit. Observe pyRevit tabs do not appear.
Run pyrevit env in command prompt. Observe empty Registered Clones and Attachments sections.
Manually register and attach via CLI:

   pyrevit clones add master "C:\Program Files\pyRevit-Master" --force
   pyrevit attach master default --installed --allusers

Open Revit. pyRevit tabs now appear.
Run any extension tool that calls pyrevit.forms to display a WPF dialog.
Observe ResourceReferenceKeyNotFoundException crash.
Uninstall 6.0.0, reinstall 5.3.1.25308. All tools work correctly.

### ⏲️ Expected behavior

Admin installer should register the clone and attach to all detected Revit versions automatically.
pyrevit.forms WPF dialogs should function identically to 5.3.1.
pyrevit env should not throw null reference errors under Running Revit Instances.

### 🖥️ Hardware and Software Setup (please complete the following information)

```shell
C:\Users\jgriffith>pyrevit env
==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive/image)
master | Branch: "master" | Version: "6.0.0.26032+2145" | Path: "C:\Program Files\pyRevit-Master"
==> Attachments
master | Product: "2026 First Customer Ship" | Engine: DEFAULT | Path: "C:\Program Files\pyRevit-Master" | AllUsers
master | Product: "2025 First Customer Ship" | Engine: DEFAULT | Path: "C:\Program Files\pyRevit-Master" | AllUsers
master | Product: "2024.3.4" | Engine: DEFAULT | Path: "C:\Program Files\pyRevit-Master" | AllUsers
master | Product: "2023.1.8" | Engine: DEFAULT | Path: "C:\Program Files\pyRevit-Master" | AllUsers
master | Product: "2022.1.8" | Engine: DEFAULT | Path: "C:\Program Files\pyRevit-Master" | AllUsers
==> Installed Extensions
==> Default Extension Search Path
C:\Users\jgriffith\AppData\Roaming\pyRevit\Extensions
==> Extension Search Paths
==> Extension Sources - Default
https://github.com/pyrevitlabs/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
==> Installed Revits
2026 First Customer Ship | Version: 26.0.4.409 | Build: 20250227_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2026\"
2025 First Customer Ship | Version: 25.0.2.419 | Build: 20240307_1300(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2025\"
2024.3.4 | Version: 24.3.40.26 | Build: 20250918_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2024\"
2023.1.8 | Version: 23.1.80.30 | Build: 20250724_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2023\"
2022.1.8 | Version: 22.1.80.32 | Build: 20241107_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2022\"
==> Running Revit Instances
Error: Object reference not set to an instance of an object.
Run with "--debug" option to see debug messages
```

### Additional context

Related to #3063. The installer attachment failure and the pyrevit.forms WPF crash both appear to stem from the C# Loader rewrite (#2647). All issues are fully reproducible and all affected functionality works correctly on 5.3.1.25308.

</p>
</details>

**Comment by Wurschdhaud** [comment]
Bug 2 maybe fixed via #3100

**Comment by jmcouffin** [comment]
- Bug # 2 is fixed, confirmed
- bug 3 is irrelevant for now _  this is not blocking and is a very long standing issue when a revit version is not listed in the pyrevit hosts file. I starrted to tackle it, but still have some work on the CLI.

Thanks for reporting all of the above. The thing is here, it is harder to take care of this if you are pointing at 3 different pb in the same issue.
I will edit the orginal text and title to keep the admin installer issue alive
