### ISSUE TITLE
Revit 2021.1.5_4.8.8 Keynote Manager Window_'NoneType' object has no attribute 'Value' 

### ISSUE THREAD

**Issue by ckuhnMPLS** [eirannejad/pyRevit#1383]
Keynotes linked through Autodesk Docs. Was working well with Revit 2021.1.4. All users now getting this error opening keynote manager after being updated to 2021.1.5

**Comment by aconchado** [comment]
We just started getting this error as well. Revit 2021.1.4 and Desktop Connector 15.0.0.1540.

**Comment by nterranova-fsb** [comment]
It sounds like this issue is a duplicate of [this one](https://github.com/eirannejad/pyRevit/issues/1371)

It seems that Autodesk docs versions of 15+ break the keynote manager

**Comment by eirannejad** [comment]
Similar to https://github.com/eirannejad/pyRevit/issues/1402

**Comment by KMann08** [comment]
I've started getting this issue when trying to run Keynote Manager - Set Property 'Microsoft.Scripting.Runtime.DynamicX..... threw an Exception

DEBUG [pyrevit.versionmgr] Can not create repo from directory: C:\Users\######\AppData\Roaming\pyRevit-Master | Path 'C:\Users\######\AppData\Roaming\pyRevit-Master' doesn't point at a valid Git repository or workdir. 

DEBUG [pyrevit.versionmgr] Can not get pyRevit patch number. | 'NoneType' object has no attribute 'last_commit_hash'
